<a href="https://colab.research.google.com/github/LatiefDataVisionary/numpy-with-w3schools/blob/main/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Numpy HOME, Introduction**

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])

In [2]:
arr

array([1, 2, 3, 4, 5])

In [3]:
type(arr)

numpy.ndarray

In [5]:
np.__version__

'1.26.4'

### **NumPy Creating Arrays**



Create a NumPy ndarray Object


In [6]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

Use a tuple to create a NumPy array:

In [8]:
arr = np.array((1,2,3,4,5))
arr

array([1, 2, 3, 4, 5])

Dimensions in Arrays


1. 0-D Arrays


In [9]:
arr = np.array(42)
arr

array(42)

2. 1-D Arrays


In [10]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

3. 2-D Arrays


In [12]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

4. 3-D arrays


In [14]:
arr = np.array([[[1,2,3], [4,5,6]],[[1,2,3], [4,5,6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

Check Number of Dimensions?


In [19]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

In [23]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Higher Dimensional Arrays


In [31]:
arr = np.array([1,2,3,4], ndmin=5)
arr

array([[[[[1, 2, 3, 4]]]]])

In [32]:
print('Number of dimensions: ', arr.ndim)

Number of dimensions:  5
