<a href="https://colab.research.google.com/github/LatiefDataVisionary/numpy-with-w3schools/blob/main/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Numpy HOME, Introduction**

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])

In [2]:
arr

array([1, 2, 3, 4, 5])

In [3]:
type(arr)

numpy.ndarray

In [4]:
np.__version__

'1.26.4'

### **NumPy Creating Arrays**



Create a NumPy ndarray Object


In [5]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

Use a tuple to create a NumPy array:

In [7]:
arr = np.array((1,2,3,4,5))
arr

array([1, 2, 3, 4, 5])

Dimensions in Arrays


1. 0-D Arrays


In [8]:
arr = np.array(42)
arr

array(42)

2. 1-D Arrays


In [9]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

3. 2-D Arrays


In [10]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

4. 3-D arrays


In [11]:
arr = np.array([[[1,2,3], [4,5,6]],[[1,2,3], [4,5,6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

Check Number of Dimensions?


In [12]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

In [13]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Higher Dimensional Arrays


In [14]:
arr = np.array([1,2,3,4], ndmin=5)
arr

array([[[[[1, 2, 3, 4]]]]])

In [15]:
print('Number of dimensions: ', arr.ndim)

Number of dimensions:  5


### **Access Array Elements**


In [17]:
arr = np.array([1,2,3,4])
arr[0]

1

In [20]:
arr = np.array([1,2,3,4])
arr[2] + arr[3]

7

Access 2-D Arrays


In [25]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0,1])
print(arr[1,2])
print(arr[0,4])
print(arr[1,3])

2
8
5
9


Access 3-D Arrays


In [27]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr[0,1,2])
print(arr[1,1,2])

6
12


Negative Indexing


In [31]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, -1])
print(arr[0, -4])
print(arr[1, -3])

10
2
8


### **NumPy Array Slicing**


Slicing arrays


In [32]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]


Negative Slicing


In [34]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])
print(arr[-4:-1])
print(arr[-5:-3])

[5 6]
[4 5 6]
[3 4]


STEP

In [35]:
arr = np.array([1, 2, 3, 4, 5, 6, 7,8,9,])
print(arr[1:5:2])

[2 4]


In [41]:
arr_range = np.arange(1, 100)
arr_range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [42]:
arr_range[6:47:3]

array([ 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46])

In [43]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


In [45]:
arr_range[::3]

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

Slicing 2-D Arrays


In [46]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [47]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [48]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


### **NumPy Data Types**


Checking the Data Type of an Array


In [49]:
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int64')

In [50]:
arr = np.array(['apple', 'banana', 'cherry'])
arr.dtype

dtype('<U6')

Creating Arrays With a Defined Data Type


In [51]:
arr = np.array([1,2,3,4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [52]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


A non integer string like 'a' can not be converted to integer (will raise an error):



In [53]:
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [55]:
arr = np.array(['1', '2', '3'], dtype='i')
arr

array([1, 2, 3], dtype=int32)

Converting Data Type on Existing Arrays


In [57]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')

print(arr)
print(newarr)
print(newarr.dtype)

[1.1 2.1 3.1]
[1 2 3]
int32


In [58]:
arr = np.array([1,0,3])
newarr = arr.astype(bool)

print(arr)
print(newarr)
print(newarr.dtype)

[1 0 3]
[ True False  True]
bool
