<a href="https://colab.research.google.com/github/LatiefDataVisionary/numpy-with-w3schools/blob/main/numpy_random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**1. Random Numbers in NumPy**


### **A. Generate Random Number**

Generate a random integer from 0 to 100:



In [4]:
from numpy import random
x = random.randint(100)
x

35

### **B. Generate Random Float**

The random module's rand() method returns a random float between 0 and 1.



In [3]:
x = random.rand()
x

0.6497232421102888

### **C. Generate Random Array**

The randint() method takes a size parameter where you can specify the shape of an array.




In [5]:
x = random.randint(100, size=(5))
x

array([79, 26, 90, 22, 55])

Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:



In [6]:
x = random.randint(100, size=(3,5))
x

array([[12, 43, 98, 91, 52],
       [76, 53, 81, 77, 24],
       [89, 83, 34, 11, 63]])

In [11]:
x = random.randint(100, size=(2,5,3))
x

array([[[82, 69, 24],
        [19, 58, 39],
        [36, 40, 46],
        [18, 33, 46],
        [26, 89, 67]],

       [[16,  4, 75],
        [37, 13,  2],
        [24, 83, 85],
        [69, 90, 71],
        [75, 22, 69]]])

### **D. Floats**


Generate a 1-D array containing 5 random floats:



In [13]:
x = random.rand(5)
x

array([0.14293518, 0.84074953, 0.73504177, 0.4209326 , 0.73955375])

Generate a 2-D array with 3 rows, each row containing 5 random numbers:



In [16]:
x = random.rand(3,5)
x

array([[0.15728175, 0.51260043, 0.51548604, 0.84234491, 0.12782235],
       [0.10765733, 0.42762858, 0.66092961, 0.23587109, 0.07914281],
       [0.02192218, 0.33907755, 0.04299259, 0.17146489, 0.98593214]])

In [17]:
x[2]

array([0.02192218, 0.33907755, 0.04299259, 0.17146489, 0.98593214])

**E. Generate Random Number From Array**

Return one of the values in an array:




In [22]:
x = random.choice([3,5,7,9])
x

7

Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):



In [25]:
x = random.choice([3,5,7,9], size=(3,5))
x

array([[3, 7, 9, 5, 3],
       [9, 9, 7, 7, 7],
       [9, 9, 9, 3, 9]])

# **2. Random Data Distribution**


### **A. Random Distribution**


Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.

The probability for the value to be 3 is set to be 0.1

The probability for the value to be 5 is set to be 0.3

The probability for the value to be 7 is set to be 0.6

The probability for the value to be 9 is set to be 0

In [31]:
x = random.choice([3,5,7,9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
x

array([3, 7, 3, 7, 7, 3, 7, 7, 5, 7, 5, 7, 7, 7, 7, 7, 5, 5, 7, 7, 7, 7,
       7, 3, 3, 3, 5, 5, 7, 5, 3, 7, 5, 5, 5, 7, 7, 3, 7, 3, 5, 7, 7, 7,
       3, 5, 7, 5, 5, 7, 7, 7, 7, 5, 3, 3, 5, 7, 3, 7, 7, 5, 7, 7, 7, 7,
       5, 5, 3, 7, 7, 7, 7, 7, 7, 5, 7, 7, 5, 5, 3, 5, 7, 3, 5, 7, 7, 7,
       3, 3, 5, 7, 7, 3, 7, 7, 7, 7, 5, 7])

Same example as above, but return a 2-D array with 3 rows, each containing 5 values.



In [32]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))
x

array([[7, 5, 3, 7, 7],
       [5, 7, 7, 7, 5],
       [5, 7, 7, 7, 7]])